name: libenet

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: build libenet
      run: sh .github/script/build_enet.sh
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
        
    - name: Upload NETSDK Header
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: iot-p2p/components_src/eNet/extension/app/src/app_p2p.h
        asset_name: AppWrapper.h
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload NETSDK Library
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: iot-p2p/components_src/eNet/build/ios/Release-iphoneos/libenet.a
        asset_name: libenet.a
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
